@node Copying This Manual, Concept Index, Source Material, Top
@appendix Copying This Manual

This manual is covered under the GNU Free Documentation License.  A copy
of the FDL is provided here.

@menu
* GNU Free Documentation License::  License for copying this manual
@end menu

@include fdl.texi

@bye

@ignore
   arch-tag: 202c34cf-3749-4464-ac12-9599be7a40e1
@end ignore
