@node logging rotating-log, math minima, logging port-log, Top
@chapter (logging rotating-log)

@cindex logs, rotating

This module defines a log handler for text logs that rotate when they
get to be a user-defined size.  This is similar to the behavior of
many UNIX standard log files.  @xref{logging logger}, for more
information in general on log handlers.

@deftp Class <rotating-log>
This is a log handler which writes text logs that rotate when they reach
a configurable size limit.

Keywords recognized by @code{<rotating-log>} on creation are:
@table @code
@item #:num-files
This is the number of log files you want the logger to use.  Default is 4.

@item #:size-limit
This is the size, in bytes, a log file must get before the logs get
rotated.  Default is 1MB (104876 bytes).

@item #:file-name
This is the base of the log file name.   Default is ``logfile''.  Numbers will
be appended to the file name representing the log number.  The newest log
file is always ``@var{NAME}.1''.

@item #:formatter
Allows the user to provide a function to use as the log formatter for
this handler.  @xref{log handler class}, for details.
@end table

Example of creating a @code{<rotating-log>}:
@lisp
(make <rotating-log>
      #:num-files 3
      #:size-limit 1024
      #:file-name "test-log-file"))
@end lisp
@end deftp

@ignore
   arch-tag: adc722c1-2352-45d1-ba80-e160a735e906
@end ignore
