@node math primes, os process, math minima, Top
@chapter (math primes)

@cindex prime number
@cindex numbers, prime
@cindex numbers, prime factors of
@cindex prime factors
@cindex factors, prime

This module contains functions dealing with prime numbers.

@defun prime? num
Determines if @var{num} is prime, and returns @samp{#t} or @samp{#f}.
There is a 2^-30 percent chance that a composite number will be 
listed as prime, but a prime number can never be listed as composite.
@end defun

@defun prime> num
Returns the first prime number greater than @var{num}. 
@end defun

@defun primes> num amount
Returns a list of @var{amount} prime numbers greater than @var{num}.  The list will be in
ascending numerical order.
@end defun

@defun prime< num
Returns the first prime number less than @var{num}.  If there isn't a number less than
@var{num}, it returns @code{#f}.
@end defun

@defun primes< num amount
Returns a list of @var{amount} prime numbers less than @var{num}.  The list will be in
ascending numerical order.  If there are less prime numbers below @var{num} than were
asked for, then a shorter list is returned.
@end defun

@defun factor num
Returns a list of the prime factors of @var{num}.  The order of the
factors is unspecified.  In order to obtain a sorted list do
@code{(sort! (factor @var{num}) <)}.
@end defun

@ignore
   arch-tag: 29d68ba2-73f3-40e8-93a8-f70cb8aa8191
@end ignore
