@node string soundex, string transform, string completion, Top
@chapter (string soundex)

@cindex soundex
@cindex Aiza, soundex'ed

@defun soundex str
Performs the original soundex algorithm on the input @var{str}.  Returns the encoded
string.  The idea is for similar sounding sames to end up with the same encoding.

@lisp
(soundex "Aiza")
=> "A200"
(soundex "Aisa")
=> "A200"
(soundex "Aesha")
=> "A200"
@end lisp
@end defun

@ignore
   arch-tag: eed61676-309d-463f-b865-f6d6346da944
@end ignore
